name: Model-CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

permissions:
  contents: write
  pull-requests: write

jobs:
  test-and-report:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5.0.0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Pull data and model from DVC
        run: |
          dvc pull

      - name: Run Pytest and Generate Artifacts
        run: |
          pytest

      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Pytest Results" > report.md          
          echo "Model Evaluation" >> report.md
          echo "![Confusion Matrix](confusion_matrix.png)" >> report.md

          cml comment create report.md