name: Model-CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  test-and-report:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5.0.0

      - name: Setup CML (Continuous Machine Learning)
        uses: iterative/setup-cml@v2.0.1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Pull data and model from DVC
        run: |
          dvc pull

      - name: Run Pytest
        run: |
          pytest -v &> report.txt
          cat report.txt

      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo 'hello' >> report.md
          echo 'Hi' >> report.md
          cml comment create report.md
